domain: shahmishal.github.io
url: https://shahmishal.github.io/swift-org-website/pr-preview/pr-1
baseurl: /swift-org-website/pr-preview/pr-1
title: Swift.org
description: "Swift is a general-purpose programming language built using a modern approach to safety, performance, and software design patterns."
timezone: America/Lower_Princes
exclude: ["README.md", "config.ru", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
safe: false
future: true
basewebsite: /swift-org-website/pr-preview/pr-1


kramdown:
    syntax_highlighter: rouge

sass:
    style: compressed
    sass_dir: "assets/stylesheets"

defaults:
    -
        scope:
            type: "posts"
        values:
            permalink: /blog/:title/
            layout: "post"

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

include:
 - .well-known
